#配置端口号
server:
  port: 6003
#配置名称
spring:
  application:
    name: eureka-server
#防止eureka向自己注册
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
security:
  user:
    name: admin
    password: admin123